export const menuItems = [
    { icon: 'table_chart_view', label: 'OI Tracker', href: '/oi/tracker' },
    { icon: 'search', label: 'Lookup', href: '/oi/lookup' },
    { icon: 'visibility', label: 'OI Glimps', href: '/oi/glimpse' },
    { icon: 'table_chart', label: 'Buildup', href: '/oi/buildup' },
    { icon: 'monitoring', label: 'Call vs Put', href: '/oi/call-vs-put' },
    { icon: 'multiline_chart', label: 'Multi OI', href: '/oi/multi-call-vs-put' },
    { icon: 'health_and_safety', label: 'Max Pain', href: '/oi/max-pain' },
    { icon: 'query_stats', label: 'Straddle Analysis', href: '/charts/straddle' },
    { icon: 'stacked_line_chart', label: 'Strangle Analysis', href: '/charts/strangle' },
    { icon: 'waves', label: 'Air In Premiums', href: '/charts/air-in-premiums' },
    { icon: 'screen_search_desktop', label: 'Stocks Screeners', href: '/stocks/stocks-screener' },
    { icon: 'trending_up', label: '52-Week Breakout', href: '/stocks/breakout/52-week' },
    { icon: 'bar_chart', label: 'Volume Breakout', href: '/stocks/breakout/volume' },
    { icon: 'monitor_heart', label: 'Market Pulse', href: '/market-pulse' },
];