PRE_DEFINED_WATCHLIST = ("Indices", "Nifty 50", "Nifty Bank")

INDICES = [
    "SKT:1:1:NIFTY",
    "SKT:1:1:BANKNIFTY",
    "SKT:1:1:MIDCPNIFTY",
    "SKT:1:1:FINNIFTY",
    "SKT:1:1:NIFTYNXT50",
    "SKT:2:1:SENSEX",
    "SKT:2:1:BANKEX",
    "SKT:2:1:SENSEX50",
]

NIFTY_50 = [
    "SKT:1:2:ADANIENT-EQ",
    "SKT:1:2:ADANIPORTS-EQ",
    "SKT:1:2:APOLLOHOSP-EQ",
    "SKT:1:2:ASIANPAINT-EQ",
    "SKT:1:2:AXISBANK-EQ",
    "SKT:1:2:BAJAJ-AUTO-EQ",
    "SKT:1:2:BAJFINANCE-EQ",
    "SKT:1:2:BAJAJFINSV-EQ",
    "SKT:1:2:BEL-EQ",
    "SKT:1:2:BHARTIARTL-EQ",
    "SKT:1:2:CIPLA-EQ",
    "SKT:1:2:COALINDIA-EQ",
    "SKT:1:2:DRREDDY-EQ",
    "SKT:1:2:EICHERMOT-EQ",
    "SKT:1:2:ETERNAL-EQ",
    "SKT:1:2:GRASIM-EQ",
    "SKT:1:2:HCLTECH-EQ",
    "SKT:1:2:HDFCBANK-EQ",
    "SKT:1:2:HDFCLIFE-EQ",
    "SKT:1:2:HEROMOTOCO-EQ",
    "SKT:1:2:HINDALCO-EQ",
    "SKT:1:2:HINDUNILVR-EQ",
    "SKT:1:2:ICICIBANK-EQ",
    "SKT:1:2:ITC-EQ",
    "SKT:1:2:INDUSINDBK-EQ",
    "SKT:1:2:INFY-EQ",
    "SKT:1:2:JSWSTEEL-EQ",
    "SKT:1:2:JIOFIN-EQ",
    "SKT:1:2:KOTAKBANK-EQ",
    "SKT:1:2:LT-EQ",
    "SKT:1:2:M&M-EQ",
    "SKT:1:2:MARUTI-EQ",
    "SKT:1:2:NTPC-EQ",
    "SKT:1:2:NESTLEIND-EQ",
    "SKT:1:2:ONGC-EQ",
    "SKT:1:2:POWERGRID-EQ",
    "SKT:1:2:RELIANCE-EQ",
    "SKT:1:2:SBILIFE-EQ",
    "SKT:1:2:SHRIRAMFIN-EQ",
    "SKT:1:2:SBIN-EQ",
    "SKT:1:2:SUNPHARMA-EQ",
    "SKT:1:2:TCS-EQ",
    "SKT:1:2:TATACONSUM-EQ",
    "SKT:1:2:TATAMOTORS-EQ",
    "SKT:1:2:TATASTEEL-EQ",
    "SKT:1:2:TECHM-EQ",
    "SKT:1:2:TITAN-EQ",
    "SKT:1:2:TRENT-EQ",
    "SKT:1:2:ULTRACEMCO-EQ",
    "SKT:1:2:WIPRO-EQ",
]

NIFTY_BANK = [
    "SKT:1:2:HDFCBANK-EQ",
    "SKT:1:2:ICICIBANK-EQ",
    "SKT:1:2:AXISBANK-EQ",
    "SKT:1:2:KOTAKBANK-EQ",
    "SKT:1:2:SBIN-EQ",
    "SKT:1:2:INDUSINDBK-EQ",
    "SKT:1:2:BANKBARODA-EQ",
    "SKT:1:2:PNB-EQ",
    "SKT:1:2:FEDERALBNK-EQ",
    "SKT:1:2:IDFCFIRSTB-EQ",
    "SKT:1:2:BANDHANBNK-EQ",
    "SKT:1:2:AUBANK-EQ",
]

PRE_DEFINED_TOKENS: dict[str, list[str]] = {
    "Indices": INDICES,
    "Nifty 50": NIFTY_50,
    "Nifty Bank": NIFTY_BANK,
}

COL_WATCHLIST = "watchlist"
COL_WATCHLIST_NOTES = "watchlist_notes"
MAX_NOTE_LENGTH = 500

MAX_CUSTOM_WATCHLISTS_PER_USER = 50
MAX_SYMBOLS_PER_WATCHLIST = 50

PRE_DEFINED_TOKEN_INDEX: dict[str, set[str]] = {
    n: set(toks) for n, toks in PRE_DEFINED_TOKENS.items()
}

PRE_DEFINED_ENTRIES: dict[str, list[dict]] = {
    "Indices": [
        {"sk_token": "SKT:1:1:NIFTY",      "trading_symbol": "NIFTY",      "exchange": "NSE", "instrument": "INDEX", "lot_size": 0, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_NIFTY_2026-06-02_INDEX",      "underlying_symbol": "NIFTY", "company_name": "NIFTY 50",      "ltp": 23547.75, "prev_close": 23907.15},
        {"sk_token": "SKT:1:1:BANKNIFTY",  "trading_symbol": "BANKNIFTY",  "exchange": "NSE", "instrument": "INDEX", "lot_size": 0, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_BANKNIFTY_2026-06-30_INDEX",  "underlying_symbol": "BANKNIFTY", "company_name": "NIFTY BANK",  "ltp": 54239.20, "prev_close": 55293.65},
        {"sk_token": "SKT:1:1:MIDCPNIFTY", "trading_symbol": "MIDCPNIFTY", "exchange": "NSE", "instrument": "INDEX", "lot_size": 0, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_MIDCPNIFTY_2026-06-30_INDEX", "underlying_symbol": "MIDCPNIFTY", "company_name": "NIFTY MIDCAP SELECT", "ltp": 14474.90, "prev_close": 14559.90},
        {"sk_token": "SKT:1:1:FINNIFTY",   "trading_symbol": "FINNIFTY",   "exchange": "NSE", "instrument": "INDEX", "lot_size": 0, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_FINNIFTY_2026-06-30_INDEX",   "underlying_symbol": "FINNIFTY", "company_name": "NIFTY FIN SERVICE",   "ltp": 25354.00, "prev_close": 25752.20},
        {"sk_token": "SKT:1:1:NIFTYNXT50", "trading_symbol": "NIFTYNXT50", "exchange": "NSE", "instrument": "INDEX", "lot_size": 0, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_NIFTYNXT50_2026-06-30_INDEX", "underlying_symbol": "NIFTYNXT50", "company_name": "NIFTY NEXT 50", "ltp": 71073.65, "prev_close": 71957.20},
        {"sk_token": "SKT:2:1:SENSEX",     "trading_symbol": "SENSEX",     "exchange": "BSE", "instrument": "INDEX", "lot_size": 0, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "BSE_SENSEX_2026-06-04_INDEX",     "underlying_symbol": "SENSEX", "company_name": "BSE SENSEX",     "ltp": 74775.74, "prev_close": 75867.80},
        {"sk_token": "SKT:2:1:BANKEX",     "trading_symbol": "BANKEX",     "exchange": "BSE", "instrument": "INDEX", "lot_size": 0, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "BSE_BANKEX_2026-06-25_INDEX",     "underlying_symbol": "BANKEX", "company_name": "BSE BANKEX",     "ltp": 61131.26, "prev_close": 62096.22},
        {"sk_token": "SKT:2:1:SENSEX50",   "trading_symbol": "SENSEX50",   "exchange": "BSE", "instrument": "INDEX", "lot_size": 0, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "BSE_SENSEX50_2026-06-25_INDEX",   "underlying_symbol": "SENSEX50", "company_name": "BSE SENSEX 50",   "ltp": 24625.98, "prev_close": 24742.38},
    ],
    "Nifty 50": [
        {"sk_token": "SKT:1:2:ADANIENT-EQ",   "trading_symbol": "ADANIENT",   "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_ADANIENT_2026-06-30_EQUITY",   "underlying_symbol": "ADANIENT", "company_name": "Adani Enterprises", "ltp": 2937.40,  "prev_close": 2973.10},
        {"sk_token": "SKT:1:2:ADANIPORTS-EQ", "trading_symbol": "ADANIPORTS", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_ADANIPORTS_2026-06-30_EQUITY", "underlying_symbol": "ADANIPORTS", "company_name": "Adani Ports & SEZ", "ltp": 1804.60,  "prev_close": 1811.20},
        {"sk_token": "SKT:1:2:APOLLOHOSP-EQ", "trading_symbol": "APOLLOHOSP", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_APOLLOHOSP_2026-06-30_EQUITY", "underlying_symbol": "APOLLOHOSP", "company_name": "Apollo Hospitals", "ltp": 8176.50,  "prev_close": 8258.50},
        {"sk_token": "SKT:1:2:ASIANPAINT-EQ", "trading_symbol": "ASIANPAINT", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_ASIANPAINT_2026-06-30_EQUITY", "underlying_symbol": "ASIANPAINT", "company_name": "Asian Paints", "ltp": 2671.60,  "prev_close": 2671.90},
        {"sk_token": "SKT:1:2:AXISBANK-EQ",   "trading_symbol": "AXISBANK",   "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_AXISBANK_2026-06-30_EQUITY",   "underlying_symbol": "AXISBANK", "company_name": "Axis Bank", "ltp": 1286.60,  "prev_close": 1304.10},
        {"sk_token": "SKT:1:2:BAJAJ-AUTO-EQ", "trading_symbol": "BAJAJ-AUTO", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_BAJAJ-AUTO_2026-06-30_EQUITY", "underlying_symbol": "BAJAJ-AUTO", "company_name": "Bajaj Auto", "ltp": 10460.00, "prev_close": 10593.00},
        {"sk_token": "SKT:1:2:BAJFINANCE-EQ", "trading_symbol": "BAJFINANCE", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_BAJFINANCE_2026-06-30_EQUITY", "underlying_symbol": "BAJFINANCE", "company_name": "Bajaj Finance", "ltp": 908.25,   "prev_close": 931.15},
        {"sk_token": "SKT:1:2:BAJAJFINSV-EQ", "trading_symbol": "BAJAJFINSV", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_BAJAJFINSV_2026-06-30_EQUITY", "underlying_symbol": "BAJAJFINSV", "company_name": "Bajaj Finserv", "ltp": 1783.60,  "prev_close": 1809.10},
        {"sk_token": "SKT:1:2:BEL-EQ",        "trading_symbol": "BEL",        "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_BEL_2026-06-30_EQUITY",        "underlying_symbol": "BEL", "company_name": "Bharat Electronics", "ltp": 410.75,   "prev_close": 419.10},
        {"sk_token": "SKT:1:2:BHARTIARTL-EQ", "trading_symbol": "BHARTIARTL", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_BHARTIARTL_2026-06-30_EQUITY", "underlying_symbol": "BHARTIARTL", "company_name": "Bharti Airtel", "ltp": 1829.00,  "prev_close": 1852.20},
        {"sk_token": "SKT:1:2:CIPLA-EQ",      "trading_symbol": "CIPLA",      "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_CIPLA_2026-06-30_EQUITY",      "underlying_symbol": "CIPLA", "company_name": "Cipla", "ltp": 1401.00,  "prev_close": 1418.20},
        {"sk_token": "SKT:1:2:COALINDIA-EQ",  "trading_symbol": "COALINDIA",  "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_COALINDIA_2026-06-30_EQUITY",  "underlying_symbol": "COALINDIA", "company_name": "Coal India", "ltp": 457.90,   "prev_close": 463.05},
        {"sk_token": "SKT:1:2:DRREDDY-EQ",    "trading_symbol": "DRREDDY",    "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_DRREDDY_2026-06-30_EQUITY",    "underlying_symbol": "DRREDDY", "company_name": "Dr Reddys Laboratories", "ltp": 1303.50,  "prev_close": 1319.00},
        {"sk_token": "SKT:1:2:EICHERMOT-EQ",  "trading_symbol": "EICHERMOT",  "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_EICHERMOT_2026-06-30_EQUITY",  "underlying_symbol": "EICHERMOT", "company_name": "Eicher Motors", "ltp": 7177.00,  "prev_close": 7419.00},
        {"sk_token": "SKT:1:2:ETERNAL-EQ",    "trading_symbol": "ETERNAL",    "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_ETERNAL_2026-06-30_EQUITY",    "underlying_symbol": "ETERNAL", "company_name": "Eternal", "ltp": 250.58,   "prev_close": 256.51},
        {"sk_token": "SKT:1:2:GRASIM-EQ",     "trading_symbol": "GRASIM",     "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_GRASIM_2026-06-30_EQUITY",     "underlying_symbol": "GRASIM", "company_name": "Grasim Industries",      "ltp": 3122.40,  "prev_close": 3165.00},
        {"sk_token": "SKT:1:2:HCLTECH-EQ",    "trading_symbol": "HCLTECH",    "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_HCLTECH_2026-06-30_EQUITY",    "underlying_symbol": "HCLTECH", "company_name": "HCL Technologies",     "ltp": 1183.80,  "prev_close": 1165.20},
        {"sk_token": "SKT:1:2:HDFCBANK-EQ",   "trading_symbol": "HDFCBANK",   "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_HDFCBANK_2026-06-30_EQUITY",   "underlying_symbol": "HDFCBANK", "company_name": "HDFC Bank", "ltp": 744.55,   "prev_close": 758.65},
        {"sk_token": "SKT:1:2:HDFCLIFE-EQ",   "trading_symbol": "HDFCLIFE",   "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_HDFCLIFE_2026-06-30_EQUITY",   "underlying_symbol": "HDFCLIFE", "company_name": "HDFC Life Insurance", "ltp": 594.80,   "prev_close": 618.85},
        {"sk_token": "SKT:1:2:HEROMOTOCO-EQ", "trading_symbol": "HEROMOTOCO", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_HEROMOTOCO_2026-06-30_EQUITY", "underlying_symbol": "HEROMOTOCO", "company_name": "Hero Motocorp", "ltp": 4903.00,  "prev_close": 5075.00},
        {"sk_token": "SKT:1:2:HINDALCO-EQ",   "trading_symbol": "HINDALCO",   "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_HINDALCO_2026-06-30_EQUITY",   "underlying_symbol": "HINDALCO", "company_name": "Hindalco Industries", "ltp": 1126.70,  "prev_close": 1099.60},
        {"sk_token": "SKT:1:2:HINDUNILVR-EQ", "trading_symbol": "HINDUNILVR", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_HINDUNILVR_2026-06-30_EQUITY", "underlying_symbol": "HINDUNILVR", "company_name": "Hindustan Unilever", "ltp": 2153.50,  "prev_close": 2198.40},
        {"sk_token": "SKT:1:2:ICICIBANK-EQ",  "trading_symbol": "ICICIBANK",  "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_ICICIBANK_2026-06-30_EQUITY",  "underlying_symbol": "ICICIBANK", "company_name": "ICICI Bank",   "ltp": 1256.40,  "prev_close": 1279.10},
        {"sk_token": "SKT:1:2:ITC-EQ",        "trading_symbol": "ITC",        "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_ITC_2026-06-30_EQUITY",        "underlying_symbol": "ITC", "company_name": "ITC",         "ltp": 286.90,   "prev_close": 291.95},
        {"sk_token": "SKT:1:2:INDUSINDBK-EQ", "trading_symbol": "INDUSINDBK", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_INDUSINDBK_2026-06-30_EQUITY", "underlying_symbol": "INDUSINDBK", "company_name": "Indusind Bank", "ltp": 914.35,   "prev_close": 932.30},
        {"sk_token": "SKT:1:2:INFY-EQ",       "trading_symbol": "INFY",       "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_INFY_2026-06-30_EQUITY",       "underlying_symbol": "INFY", "company_name": "Infosys",        "ltp": 1160.90,  "prev_close": 1159.90},
        {"sk_token": "SKT:1:2:JSWSTEEL-EQ",   "trading_symbol": "JSWSTEEL",   "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_JSWSTEEL_2026-06-30_EQUITY",   "underlying_symbol": "JSWSTEEL", "company_name": "JSW Steel", "ltp": 1278.00,  "prev_close": 1309.30},
        {"sk_token": "SKT:1:2:JIOFIN-EQ",     "trading_symbol": "JIOFIN",     "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_JIOFIN_2026-06-30_EQUITY",     "underlying_symbol": "JIOFIN", "company_name": "Jio Financial Services",      "ltp": 238.95,   "prev_close": 242.89},
        {"sk_token": "SKT:1:2:KOTAKBANK-EQ",  "trading_symbol": "KOTAKBANK",  "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_KOTAKBANK_2026-06-30_EQUITY",  "underlying_symbol": "KOTAKBANK", "company_name": "Kotak Bank",   "ltp": 384.20,   "prev_close": 388.70},
        {"sk_token": "SKT:1:2:LT-EQ",         "trading_symbol": "LT",         "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_LT_2026-06-30_EQUITY",         "underlying_symbol": "LT", "company_name": "Larsen & Toubro",          "ltp": 4076.50,  "prev_close": 4047.50},
        {"sk_token": "SKT:1:2:M&M-EQ",        "trading_symbol": "M&M",        "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_M&M_2026-06-30_EQUITY",        "underlying_symbol": "M&M", "company_name": "Mahindra & Mahindra",         "ltp": 3045.60,  "prev_close": 3121.60},
        {"sk_token": "SKT:1:2:MARUTI-EQ",     "trading_symbol": "MARUTI",     "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_MARUTI_2026-06-30_EQUITY",     "underlying_symbol": "MARUTI", "company_name": "Maruti Suzuki",      "ltp": 13127.00, "prev_close": 13364.00},
        {"sk_token": "SKT:1:2:NTPC-EQ",       "trading_symbol": "NTPC",       "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_NTPC_2026-06-30_EQUITY",       "underlying_symbol": "NTPC", "company_name": "NTPC",        "ltp": 386.90,   "prev_close": 398.15},
        {"sk_token": "SKT:1:2:NESTLEIND-EQ",  "trading_symbol": "NESTLEIND",  "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_NESTLEIND_2026-06-30_EQUITY",  "underlying_symbol": "NESTLEIND", "company_name": "Nestle",   "ltp": 1421.50,  "prev_close": 1406.50},
        {"sk_token": "SKT:1:2:ONGC-EQ",       "trading_symbol": "ONGC",       "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_ONGC_2026-06-30_EQUITY",       "underlying_symbol": "ONGC", "company_name": "Oil & Natural Gas Corporation",        "ltp": 265.40,   "prev_close": 274.05},
        {"sk_token": "SKT:1:2:POWERGRID-EQ",  "trading_symbol": "POWERGRID",  "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_POWERGRID_2026-06-30_EQUITY",  "underlying_symbol": "POWERGRID", "company_name": "Power Grid Corporation of India",   "ltp": 290.55,   "prev_close": 300.15},
        {"sk_token": "SKT:1:2:RELIANCE-EQ",   "trading_symbol": "RELIANCE",   "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_RELIANCE_2026-06-30_EQUITY",   "underlying_symbol": "RELIANCE", "company_name": "Reliance Industries", "ltp": 1321.20,  "prev_close": 1350.50},
        {"sk_token": "SKT:1:2:SBILIFE-EQ",    "trading_symbol": "SBILIFE",    "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_SBILIFE_2026-06-30_EQUITY",    "underlying_symbol": "SBILIFE", "company_name": "SBI Life Insurance",     "ltp": 1830.10,  "prev_close": 1901.90},
        {"sk_token": "SKT:1:2:SHRIRAMFIN-EQ", "trading_symbol": "SHRIRAMFIN", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_SHRIRAMFIN_2026-06-30_EQUITY", "underlying_symbol": "SHRIRAMFIN", "company_name": "Shriram Finance", "ltp": 947.15,   "prev_close": 963.20},
        {"sk_token": "SKT:1:2:SBIN-EQ",       "trading_symbol": "SBIN",       "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_SBIN_2026-06-30_EQUITY",       "underlying_symbol": "SBIN", "company_name": "State Bank of India",        "ltp": 964.40,   "prev_close": 968.50},
        {"sk_token": "SKT:1:2:SUNPHARMA-EQ",  "trading_symbol": "SUNPHARMA",  "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_SUNPHARMA_2026-06-30_EQUITY",  "underlying_symbol": "SUNPHARMA", "company_name": "Sun Pharmaceutical",   "ltp": 1799.20,  "prev_close": 1844.30},
        {"sk_token": "SKT:1:2:TCS-EQ",        "trading_symbol": "TCS",        "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_TCS_2026-06-30_EQUITY",        "underlying_symbol": "TCS", "company_name": "Tata Consultancy Services",         "ltp": 2258.90,  "prev_close": 2284.20},
        {"sk_token": "SKT:1:2:TATACONSUM-EQ", "trading_symbol": "TATACONSUM", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_TATACONSUM_2026-06-30_EQUITY", "underlying_symbol": "TATACONSUM", "company_name": "Tata Consumer Products", "ltp": 1178.40,  "prev_close": 1194.90},
        {"sk_token": "SKT:1:2:TATAMOTORS-EQ", "trading_symbol": "TATAMOTORS", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_TATAMOTORS_2026-06-30_EQUITY", "underlying_symbol": "TATAMOTORS", "company_name": "Tata Motors", "ltp": 924.45,   "prev_close": 926.60},
        {"sk_token": "SKT:1:2:TATASTEEL-EQ",  "trading_symbol": "TATASTEEL",  "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_TATASTEEL_2026-06-30_EQUITY",  "underlying_symbol": "TATASTEEL", "company_name": "Tata Steel",   "ltp": 208.02,   "prev_close": 214.70},
        {"sk_token": "SKT:1:2:TECHM-EQ",      "trading_symbol": "TECHM",      "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_TECHM_2026-06-30_EQUITY",      "underlying_symbol": "TECHM", "company_name": "Tech Mahindra",       "ltp": 1483.90,  "prev_close": 1455.60},
        {"sk_token": "SKT:1:2:TITAN-EQ",      "trading_symbol": "TITAN",      "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_TITAN_2026-06-30_EQUITY",      "underlying_symbol": "TITAN", "company_name": "Titan",       "ltp": 4074.90,  "prev_close": 4137.90},
        {"sk_token": "SKT:1:2:TRENT-EQ",      "trading_symbol": "TRENT",      "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_TRENT_2026-06-30_EQUITY",      "underlying_symbol": "TRENT", "company_name": "Trent",       "ltp": 4224.00,  "prev_close": 4248.60},
        {"sk_token": "SKT:1:2:ULTRACEMCO-EQ", "trading_symbol": "ULTRACEMCO", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_ULTRACEMCO_2026-06-30_EQUITY", "underlying_symbol": "ULTRACEMCO", "company_name": "UltraTech Cement", "ltp": 11482.00, "prev_close": 11689.00},
        {"sk_token": "SKT:1:2:WIPRO-EQ",      "trading_symbol": "WIPRO",      "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_WIPRO_2026-06-30_EQUITY",      "underlying_symbol": "WIPRO", "company_name": "Wipro",       "ltp": 204.25,   "prev_close": 201.58},
    ],
    "Nifty Bank": [
        {"sk_token": "SKT:1:2:HDFCBANK-EQ",   "trading_symbol": "HDFCBANK",   "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_HDFCBANK_2026-06-30_EQUITY",   "underlying_symbol": "HDFCBANK", "company_name": "HDFC Bank", "ltp": 744.55,  "prev_close": 758.65},
        {"sk_token": "SKT:1:2:ICICIBANK-EQ",  "trading_symbol": "ICICIBANK",  "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_ICICIBANK_2026-06-30_EQUITY",  "underlying_symbol": "ICICIBANK", "company_name": "ICICI Bank",   "ltp": 1256.40, "prev_close": 1279.10},
        {"sk_token": "SKT:1:2:AXISBANK-EQ",   "trading_symbol": "AXISBANK",   "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_AXISBANK_2026-06-30_EQUITY",   "underlying_symbol": "AXISBANK", "company_name": "Axis Bank", "ltp": 1286.60, "prev_close": 1304.10},
        {"sk_token": "SKT:1:2:KOTAKBANK-EQ",  "trading_symbol": "KOTAKBANK",  "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_KOTAKBANK_2026-06-30_EQUITY",  "underlying_symbol": "KOTAKBANK", "company_name": "Kotak Bank",   "ltp": 384.20,  "prev_close": 388.70},
        {"sk_token": "SKT:1:2:SBIN-EQ",       "trading_symbol": "SBIN",       "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_SBIN_2026-06-30_EQUITY",       "underlying_symbol": "SBIN", "company_name": "State Bank of India",        "ltp": 964.40,  "prev_close": 968.50},
        {"sk_token": "SKT:1:2:INDUSINDBK-EQ", "trading_symbol": "INDUSINDBK", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_INDUSINDBK_2026-06-30_EQUITY", "underlying_symbol": "INDUSINDBK", "company_name": "Indusind Bank", "ltp": 914.35,  "prev_close": 932.30},
        {"sk_token": "SKT:1:2:BANKBARODA-EQ", "trading_symbol": "BANKBARODA", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_BANKBARODA_2026-06-30_EQUITY", "underlying_symbol": "BANKBARODA", "company_name": "Bank of Baroda", "ltp": 268.50,  "prev_close": 270.95},
        {"sk_token": "SKT:1:2:PNB-EQ",        "trading_symbol": "PNB",        "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_PNB_2026-06-30_EQUITY",        "underlying_symbol": "PNB", "company_name": "Punjab National Bank",         "ltp": 106.05,  "prev_close": 106.67},
        {"sk_token": "SKT:1:2:FEDERALBNK-EQ", "trading_symbol": "FEDERALBNK", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_FEDERALBNK_2026-06-30_EQUITY", "underlying_symbol": "FEDERALBNK", "company_name": "Federal Bank", "ltp": 288.95,  "prev_close": 288.90},
        {"sk_token": "SKT:1:2:IDFCFIRSTB-EQ", "trading_symbol": "IDFCFIRSTB", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_IDFCFIRSTB_2026-06-30_EQUITY", "underlying_symbol": "IDFCFIRSTB", "company_name": "IDFC First Bank", "ltp": 71.32,   "prev_close": 71.48},
        {"sk_token": "SKT:1:2:BANDHANBNK-EQ", "trading_symbol": "BANDHANBNK", "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_BANDHANBNK_2026-06-30_EQUITY", "underlying_symbol": "BANDHANBNK", "company_name": "Bandhan Bank", "ltp": 208.30,  "prev_close": 205.83},
        {"sk_token": "SKT:1:2:AUBANK-EQ",     "trading_symbol": "AUBANK",     "exchange": "NSE", "instrument": "EQUITY", "lot_size": 1, "expiry": None, "expiry_type": None, "strike": None, "option_chain_id": "NSE_AUBANK_2026-06-30_EQUITY",     "underlying_symbol": "AUBANK", "company_name": "AU Small Finance Bank",      "ltp": 984.70,  "prev_close": 1005.00},
    ],
}